### ISSUE TITLE
Connecting the Alerts table with handlebars on index.html

### ISSUE THREAD

**Issue by ArthurSmid** [OpenEugene/little-help-book-web#135]
On the work in progress there's a template with sample text for an alert, this feature allows White Bird to highlight new information, especially emergency resources in times of crisis. Here's a screen shot to clarify what part of the homepage I'm referring to, the light blue box here:
![alert-style](https://user-images.githubusercontent.com/20653086/98757756-0d40c000-2382-11eb-9c63-5f69d0bdd86d.jpg)

And this is a screen shot of the table where the information would be entered: 
![Airtable-alerts](https://user-images.githubusercontent.com/20653086/98757934-614ba480-2382-11eb-9ed3-4c78ad523e8c.jpg)

This box might not always have an alert scheduled, they have start and stop times. At times when no alert is scheduled, the blue box won't be on the homepage with alert info. A how-to could be added to the Readme to clarify how this feature is used, explaining how to enter an alert and set the start and end times in the table.

**Comment by colindavey** [comment]
Added handlebars support in branch feature/alerts. Still some issues:

- The note field has urls, and they are not appearing as proper links on the page. When they are edited in the database to add the html tags (a href=), the html isn't being rendered properly on the page. For example, '<' gets changed to &lt. Even if it were working, it would require the data-entry people to know how to add the tags. Even if they did, it would still be an error-prone process because the Airtable UI isn't good for that type of editing. 
- The rows need to be filtered so only current alerts are shown. (Current date is between start and end date.) Possible solution: Show all items in table without filtering, with data-entry team being responsible for making sure only valid items are in the table. UPDATE: Can assume that any existing rows are valid and should display, ie, no need to filter. 
- The hardcoded example is still in place. Good to keep it there as an example for now, but need to remove before it's all over.

**Comment by frankylee** [comment]
Alert notes are now being converted from Markdown to Html and successfully rendered by Handlebars.

Still needs to be filtered by Start/End dates.

**Comment by colindavey** [comment]
Great Frankylee! 

I think we decided that filtering isn't necessary, and instead, the data-entry folks will make sure only up-to-date items exist in the table.
