### ISSUE TITLE
GeoCode the service addresses

### ISSUE THREAD

**Issue by markdav-is** [OpenEugene/little-help-book-web#152]
- [ ] download a csv from the airtable GeoCode Download view.
 - [ ] geocode the addresses using your geocoding service of choice.
 - [ ] copy and paste the lat/long back into Airtable using the GeoCode Update view 

![image](https://user-images.githubusercontent.com/311063/102258474-d3079880-3ec2-11eb-9e2c-6d1d8d7cec48.png)
![image](https://user-images.githubusercontent.com/311063/102258717-0d713580-3ec3-11eb-96c1-b3d2e58ff3c1.png)
[Help Services-GeoCode Download.zip](https://github.com/OpenEugene/little-help-book-web/files/5697908/Help.Services-GeoCode.Download.zip)

**Comment by ArthurSmid** [comment]
I added a field of Geocode-ready addresses to GeoCode Download view, with all the addresses cleaned up of parenthetical descriptive text, and each now includes the state. For services provided by telephone or online, the cells are blank rather than including the text description. Our website will have a human-readable location field to populate the website because some of the locations are virtual (phone or website only) and a few of the physical addresses from the Little Help Book include plain language such as "Between Washington St and Jefferson St at 1st Ave (near skatepark bathrooms)" and "On Olive Street, behind Eugene Public Library".

**Comment by markdav-is** [comment]
For things that are not address, I suggest adding a field like "wayfinding" that help folks find thier way.  I would keep the address field to only addresses and not "overload" it with wayfinding notes.  It's easy for the UI to show one or the other or both as needed.
